{% set name = "jsonnetfmt" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/go-jsonnet/archive/v{{ version }}.tar.gz
  sha256: bf9923a848dba65fa99f6e926221ab4222c2f259ba837d279b43917962bc7d70

build:
  number: 0
  script:
    - cd cmd/jsonnetfmt && go-licenses save . --save_path ../../library_licenses
    - go build -v -o $PREFIX/bin/jsonnetfmt  # [not win]
    - go install -v .  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - jsonnetfmt --help

about:
  home: https://github.com/google/go-jsonnet
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: Jsonnet reformatter

extra:
  recipe-maintainers:
    - swenger
    - borchero
