{% set name = "jsonnetfmt" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/go-jsonnet/archive/v{{ version }}.tar.gz
  sha256: ee7aa004e78fb49608bcf28142a7494dc204a07cc07d323dd2cff3d97298c696

build:
  number: 1
  script:
    - cd cmd/jsonnetfmt && go-licenses save . --save_path ../../library_licenses
    - go build -v -o $PREFIX/bin/jsonnetfmt  # [not win]
    - go install -v .  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - jsonnetfmt --help

about:
  home: https://github.com/google/go-jsonnet
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: Jsonnet reformatter

extra:
  recipe-maintainers:
    - swenger
    - borchero
